In [23]:
import numpy as np
import pandas as pd
from pathlib import Path
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder
import numpy as np

In [2]:
train_df = pd.read_csv(Path('Resources/2019loans.csv'))
test_df = pd.read_csv(Path('Resources/2020Q1loans.csv'))

In [20]:
train_df['loan_status'].value_counts()

low_risk     6090
high_risk    6090
Name: loan_status, dtype: int64

In [27]:
X_train = train_df.drop('loan_status', axis=1)
X_train

Unnamed: 0   index  loan_amnt  int_rate  installment home_ownership  \
0           57107   57107    13375.0    0.1797       483.34       MORTGAGE   
1          141451  141451    21000.0    0.1308       478.68       MORTGAGE   
2          321143  321143    20000.0    0.1240       448.95       MORTGAGE   
3           11778   11778     3000.0    0.1240       100.22           RENT   
4          169382  169382    30000.0    0.1612      1056.49       MORTGAGE   
...           ...     ...        ...       ...          ...            ...   
12175      354912  354912    19975.0    0.2565       801.09           RENT   
12176      354944  354944    15000.0    0.1774       540.34           RENT   
12177      354973  354973     3600.0    0.1862       131.28           RENT   
12178      355002  355002    15000.0    0.0881       475.68       MORTGAGE   
12179      355307  355307    15000.0    0.1774       540.34           RENT   

       annual_inc verification_status pymnt_plan    dti  ...  pct_tl_nvr_dlq  \
0        223000.0        Not Verified          n  29.99  ...           100.0   
1        123000.0     Source Verified          n  11.26  ...            85.0   
2        197000.0     Source Verified          n  11.28  ...            85.7   
3         45000.0        Not Verified          n  18.08  ...           100.0   
4        133000.0     Source Verified          n  27.77  ...           100.0   
...           ...                 ...        ...    ...  ...             ...   
12175     28000.0        Not Verified          n  28.42  ...           100.0   
12176     50000.0            Verified          n  23.43  ...            90.5   
12177     60000.0        Not Verified          n  28.80  ...           100.0   
12178     62000.0     Source Verified          n  11.44  ...           100.0   
12179     54080.0        Not Verified          n  21.66  ...            90.0   

       percent_bc_gt_75  pub_rec_bankruptcies  tax_liens  tot_hi_cred_lim  \
0                  50.0                   0.0        0.0         577150.0   
1                  33.3                   0.0        0.0         132750.0   
2                  33.3                   0.0        0.0         628160.0   
3                  16.7                   1.0        0.0          42006.0   
4                  66.7                   0.0        0.0         283248.0   
...                 ...                   ...        ...              ...   
12175              16.7                   0.0        0.0          50055.0   
12176              11.1                   0.0        0.0          70324.0   
12177               0.0                   0.0        0.0          83765.0   
12178               0.0                   0.0        0.0         189930.0   
12179             100.0                   0.0        0.0          48968.0   

       total_bal_ex_mort total_bc_limit  total_il_high_credit_limit  \
0               122018.0        32000.0                    170200.0   
1                27896.0        15900.0                     35398.0   
2               114043.0        22600.0                     90340.0   
3                20761.0        19900.0                     15406.0   
4               109056.0        79500.0                     58778.0   
...                  ...            ...                         ...   
12175            28192.0        18700.0                     19055.0   
12176            57025.0        13300.0                     54824.0   
12177            55156.0        14800.0                     53065.0   
12178            23748.0         7000.0                     32930.0   
12179            29786.0         2900.0                     33968.0   

       hardship_flag  debt_settlement_flag  
0                  N                     N  
1                  N                     N  
2                  N                     N  
3                  N                     N  
4                  N                     N  
...              ...                   ...  
12175           

In [34]:
# Convert categorical data to numeric and separate target feature for training data
X_train = pd.get_dummies(X)
print(X_train.columns)
X_train.nunique()

Index(['Unnamed: 0', 'index', 'loan_amnt', 'int_rate', 'installment',
       'annual_inc', 'dti', 'delinq_2yrs', 'inq_last_6mths', 'open_acc',
       'pub_rec', 'revol_bal', 'total_acc', 'out_prncp', 'out_prncp_inv',
       'total_pymnt', 'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_amnt', 'collections_12_mths_ex_med', 'policy_code',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m',
       'open_act_il', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
       'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc',
       'all_util', 'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m',
       'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util',
       'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct',
       'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
       'mort_acc', 'mths_since_recent_bc'

Unnamed: 0                    12180
index                         12180
loan_amnt                       834
int_rate                         52
installment                    4351
                              ...  
application_type_Joint App        2
hardship_flag_N                   2
hardship_flag_Y                   2
debt_settlement_flag_N            2
debt_settlement_flag_Y            2
Length: 94, dtype: int64

In [97]:
y_train = LabelEncoder().fit_transform(train_df['loan_status'])
y_train

array([1, 1, 1, ..., 0, 0, 0])

In [ ]:
# Convert categorical data to numeric and separate target feature for testing data

In [29]:
X_test = test_df.drop('loan_status', axis=1)
X_test

Unnamed: 0  index  loan_amnt  int_rate  installment home_ownership  \
0          67991  67991    40000.0    0.0819       814.70       MORTGAGE   
1          25429  25429     6000.0    0.1524       208.70           RENT   
2          38496  38496     3600.0    0.1695       128.27           RENT   
3          19667  19667    20000.0    0.1524       478.33           RENT   
4          37505  37505     3600.0    0.1240       120.27           RENT   
...          ...    ...        ...       ...          ...            ...   
4697       77282  77282    30000.0    0.1240       673.42           RENT   
4698       77291  77291    24000.0    0.0756       747.22           RENT   
4699       77292  77292    10000.0    0.2305       387.36           RENT   
4700       77297  77297     8000.0    0.1862       205.86           RENT   
4701       77304  77304    30000.0    0.2055      1123.34           RENT   

      annual_inc verification_status pymnt_plan    dti  ...  pct_tl_nvr_dlq  \
0       140000.0        Not Verified          n  19.75  ...            97.7   
1        55000.0        Not Verified          n  11.52  ...            66.7   
2        42000.0        Not Verified          n   6.74  ...           100.0   
3       100000.0        Not Verified          n  12.13  ...           100.0   
4        50000.0        Not Verified          n  16.08  ...           100.0   
...          ...                 ...        ...    ...  ...             ...   
4697    140480.0     Source Verified          n  15.74  ...           100.0   
4698     50000.0        Not Verified          n  26.81  ...           100.0   
4699     33000.0            Verified          n  38.51  ...           100.0   
4700     38000.0     Source Verified          n  16.36  ...            95.0   
4701    180000.0     Source Verified          n  12.06  ...           100.0   

      percent_bc_gt_75  pub_rec_bankruptcies  tax_liens  tot_hi_cred_lim  \
0                  0.0                   0.0        0.0         527975.0   
1                  0.0                   0.0        0.0          34628.0   
2                  0.0                   0.0        0.0          23100.0   
3                 50.0                   0.0        0.0          56481.0   
4                 25.0                   0.0        0.0          45977.0   
...                ...                   ...        ...              ...   
4697              28.6                   0.0        0.0         159688.0   
4698               0.0                   0.0        0.0          62375.0   
4699               0.0                   0.0        0.0          43250.0   
4700               0.0                   1.0        0.0          31357.0   
4701              33.3                   0.0        0.0         218686.0   

      total_bal_ex_mort total_bc_limit  total_il_high_credit_limit  \
0               70914.0        74600.0                     99475.0   
1               23460.0         5900.0                     23628.0   
2               19183.0         7300.0                     15000.0   
3               43817.0        13800.0                     35981.0   
4               32448.0        21000.0                     24977.0   
...                 ...            ...                         ...   
4697           110873.0        48400.0                    107388.0   
4698            18928.0        13300.0                     30775.0   
4699            33022.0         8500.0                     29550.0   
4700            19595.0         1500.0                      9657.0   
4701           209389.0         5600.0                    209986.0   

      hardship_flag  debt_settlement_flag  
0                 N                     N  
1                 N                     N  
2                 N                     N  
3                 N                     N  
4                 N                     N  
...             ...                   ...  
4697              N                     N  
4698              N                   

In [35]:
# Convert categorical data to numeric and separate target feature for training data
X_test = pd.get_dummies(X_test)
print(X_test.columns)
X_test.nunique()

Index(['Unnamed: 0', 'index', 'loan_amnt', 'int_rate', 'installment',
       'annual_inc', 'dti', 'delinq_2yrs', 'inq_last_6mths', 'open_acc',
       'pub_rec', 'revol_bal', 'total_acc', 'out_prncp', 'out_prncp_inv',
       'total_pymnt', 'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_amnt', 'collections_12_mths_ex_med', 'policy_code',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m',
       'open_act_il', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
       'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc',
       'all_util', 'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m',
       'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util',
       'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct',
       'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
       'mort_acc', 'mths_since_recent_bc'

Unnamed: 0                     4702
index                          4702
loan_amnt                       581
int_rate                         21
installment                    2196
                               ... 
application_type_Individual       2
application_type_Joint App        2
hardship_flag_N                   2
hardship_flag_Y                   2
debt_settlement_flag_N            1
Length: 93, dtype: int64

In [36]:
y_test = LabelEncoder().fit_transform(test_df['loan_status'])
y_test

array([1, 1, 1, ..., 0, 0, 0])

In [ ]:
# add missing dummy variables to testing set

In [73]:
dummy_variable = []
dummy_variable2 = []

for i in X_train.columns:
    for j in X_test.columns:
        if i != j:
            dummy_variable.append(i)
            dummy_variable2.append(j)

dummy_variable = pd.DataFrame(dummy_variable)

dummy_variable2 = pd.DataFrame(dummy_variable2)

In [74]:
dummy_variable.value_counts()

Unnamed: 0                      93
open_acc_6m                     93
percent_bc_gt_75                93
pct_tl_nvr_dlq                  93
out_prncp_inv                   93
                                ..
inq_last_12m                    93
inq_fi                          93
initial_list_status_w           93
initial_list_status_f           93
verification_status_Verified    93
Length: 94, dtype: int64

In [75]:
dummy_variable2.value_counts()

Unnamed: 0                      93
open_acc_6m                     93
percent_bc_gt_75                93
pct_tl_nvr_dlq                  93
out_prncp_inv                   93
                                ..
inq_last_12m                    93
inq_fi                          93
initial_list_status_w           93
initial_list_status_f           93
verification_status_Verified    93
Length: 94, dtype: int64

In [72]:
# X_train['debt_settlement_flag_Y']
X_test['debt_settlement_flag_Y'] = 0

In [78]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, precision_recall_curve
from sklearn.preprocessing import RobustScaler

In [86]:
def Matrix(CM, Labels = ['low risk', 'HIGH risk']):
    df = pd.DataFrame(dataCM, index=labels, columns=labels)
    df.index.name='TRUE'
    df.columns.name='PREDICTION'
    df.loc['Total'] = df.sum()
    df['Total'] = df.sum(axis=1)
    return df
    

In [95]:
metrics = pd.DataFrame(index=['accuracy', 'precision', 'recall'],columns=['NULL', 'LogisticReg', 'ClassTree'])

# Metrics
---
* Accuracy: the proportion of the total number of predictions that are correct
* Precision: the proportion of positive predictions that are actually correct
* Recall: the proportion total positives predicted
---
* Accuracy: Overall how often the model predicts correctly HIGH_risk vs. low_risk
* Precision: how often the model predicts HIGH_risk correctly (True Positives / True Positives + False Positives)
* Recall: the proportion of the total number of predictions that are correct (True Positives / True Positives + False Negatives)
---
* False Positive = A person that will be predicted as HIGH_risk but is actually low_risk (eh..)
* False Negative = A person that will be predicted as low_risk but is actually HIGH_risk (very bad!!!)

In [96]:
import numpy as np

In [ ]:
y_pred_test = np.repeat(y_train.value_counts().idxmax(), y_test.size)
metrics.loc['accuracy', 'NULL'] = accuracy_score(y_pred = y_pred_test, y_true = y_test)
metrics.loc['precision', 'NULL'] = precision_score(y_pred = y_pred_test, y_true = y_test)
metrics.loc['recall', 'NULL'] = recall_score(y_pred = y_pred_test, y_true = y_test)

CM = confusion_matrix(y_pred=y_pred_test, y_true=y_test)
CMatrix(CM)

# Pre-scale Prediction

---

* I'm pretty sure that the models will not perform as well as they will with scaled data.
* Mainly because the numerical scales of the integer data is vary far apart and concentrated in those distances

In [ ]:
# Train the Logistic Regression model on the unscaled data and print the model score
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier

In [ ]:
# Train a Random Forest Classifier model and print the model score

In [ ]:
# Scale the data

In [79]:
scaler = RobustScaler().fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_train_scaled

array([[-0.78097654, -0.78097654, -0.10833333, ...,  0.        ,
         0.        ,  0.        ],
       [-0.28578642, -0.28578642,  0.4       , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.76919916,  0.76919916,  0.33333333, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.96781769,  0.96781769, -0.76      , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.96798795,  0.96798795,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.96977863,  0.96977863,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [80]:
scaler = RobustScaler().fit(X_test)
X_test_scaled = scaler.transform(X_test)
X_test_scaled

array([[ 0.69460717,  0.69460717,  1.72562554, ...,  0.        ,
         0.        ,  0.        ],
       [-0.44393173, -0.44393173, -0.62122519, ...,  0.        ,
         0.        ,  0.        ],
       [-0.09438782, -0.09438782, -0.78688525, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.94341011,  0.94341011, -0.34512511, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.94354386,  0.94354386, -0.48317515, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.94373111,  0.94373111,  1.03537532, ...,  0.        ,
         0.        ,  0.        ]])

In [ ]:
# Train the Logistic Regression model on the scaled data and print the model score

In [ ]:
# Train a Random Forest Classifier model on the scaled data and print the model score